#!/usr/bin/env bash
# Render the Homebrew formula for a stable release.
#
# The formula installs the same macOS and Linux archives published on the
# release. The checksums passed here must come from that release's SHA256SUMS
# file.
#
# Usage:
#   scripts/render-homebrew-formula.sh <tag> <darwin-arm64-sha256> \
#     <darwin-amd64-sha256> <linux-arm64-sha256> <linux-amd64-sha256> \
#     [output-path]
#
# With no output path the formula is written to stdout.
set -euo pipefail

if [ "$#" -lt 5 ] || [ "$#" -gt 6 ]; then
    echo "usage: $0 <tag> <darwin-arm64-sha256> <darwin-amd64-sha256> <linux-arm64-sha256> <linux-amd64-sha256> [output-path]" >&2
    exit 2
fi

tag="$1"
darwin_arm64_sha256="$2"
darwin_amd64_sha256="$3"
linux_arm64_sha256="$4"
linux_amd64_sha256="$5"
output="${6:-}"

repository="${GITHUB_REPOSITORY:-wojciechpolak/dproxy}"

if ! printf '%s' "$tag" | grep -Eq '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'; then
    echo "$tag is not a stable semantic version tag" >&2
    exit 1
fi

for checksum in \
    "$darwin_arm64_sha256" \
    "$darwin_amd64_sha256" \
    "$linux_arm64_sha256" \
    "$linux_amd64_sha256"; do
    if ! printf '%s' "$checksum" | grep -Eq '^[0-9a-f]{64}$'; then
        echo "a checksum is not a lowercase SHA-256 digest" >&2
        exit 1
    fi
done

formula="$(cat <<RUBY
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Wojciech Polak
#
# Generated by scripts/render-homebrew-formula.sh in wojciechpolak/dproxy and
# rewritten in full by that repository's release workflow. Edit the renderer,
# not this file.

class Dproxy < Formula
  desc "Discreet HTTPS and WebSocket proxy over ECH-protected WSS with end-to-end TLS"
  homepage "https://github.com/${repository}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/${repository}/releases/download/${tag}/dproxy_${tag}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64_sha256}"
    end

    on_intel do
      url "https://github.com/${repository}/releases/download/${tag}/dproxy_${tag}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64_sha256}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/${repository}/releases/download/${tag}/dproxy_${tag}_linux_arm64.tar.gz"
      sha256 "${linux_arm64_sha256}"
    end

    on_intel do
      url "https://github.com/${repository}/releases/download/${tag}/dproxy_${tag}_linux_amd64.tar.gz"
      sha256 "${linux_amd64_sha256}"
    end
  end

  def install
    bin.install "dproxy"
  end

  def caveats
    <<~EOS
      Configure the local client and token before starting the service:
        ~/.config/dproxy/client.toml
        ~/.config/dproxy/token

      Start the per-user service without sudo:
        brew services start dproxy

      Service logs are written to:
        #{var}/log/dproxy.log
    EOS
  end

  service do
    run [opt_bin/"dproxy", "client"]
    keep_alive true
    error_log_path var/"log/dproxy.log"
    stop_timeout 35
  end

  test do
    assert_match "dproxy v#{version}", shell_output("#{bin}/dproxy --version")
    output = shell_output("#{bin}/dproxy test 2>&1", 2)
    assert_match "the relay URL is required", output
  end
end
RUBY
)"

if [ -n "$output" ]; then
    mkdir -p "$(dirname "$output")"
    printf '%s\n' "$formula" > "$output"
    echo "wrote $output"
else
    printf '%s\n' "$formula"
fi
